{
 "title": "Device Details",
 "description": "Device Specific Dashboard With Prometheus and Loki.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Deployed Site",
    "query": {
     "query": "label_values(up{job=\"node_exporter\"}, deployed_site)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(up{job=\"node_exporter\", deployed_site=\"$site\"}, type)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(up{job=\"node_exporter\", deployed_site=\"$site\", type=\"$type\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Info ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$device: Rechability",
   "type": "stat",
   "description": "1=Up, 0=Down",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter\", deployed_site=\"$site\", type=\"$type\", name=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{\r\n  job=\"node_exporter\",\r\n  deployed_site=\"$site\",\r\n  type=\"$type\",\r\n  name=\"$device\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device Datetime",
   "type": "stat",
   "description": "Displays Device date time.",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * node_time_seconds{\r\n  job=\"node_exporter\",\r\n  deployed_site=\"$site\",\r\n  type=\"$type\",\r\n  name=\"$device\"\r\n}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Latency",
   "type": "stat",
   "description": "Latency to default gateway",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "#use blackbox_exporter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPS",
   "type": "stat",
   "description": "Is GPS Connected?\nIs /dev/ublox_gnss File present?",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# here check if that device file is present or not # use blackbox_exporter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Seen (ago)",
   "type": "stat",
   "description": "Last Seen Duration. > 60s:yellow, >5m:red else green",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() \r\n-\r\nmax_over_time(\r\n  timestamp(\r\n    up{job=\"node_exporter\", deployed_site=\"$site\", type=\"$type\", name=\"$device\"} == 1\r\n  )[48h:]\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "8.8.8.8 Latency",
   "type": "stat",
   "description": "Latency to 8.8.8.8",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "#use blackbox_exporter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RTK",
   "type": "stat",
   "description": "Displayed RTK value.\n-1 NO DGPS\n0 DGPS\n1 FLOAT\n2 FIX",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "#use blackbox_exporter", "legendFormat": "__auto" }
   ]
  },
  { "title": "Guages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "description": "Max hwmon Temperature",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (\r\n  node_hwmon_temp_celsius{\r\n    job=\"node_exporter\",\r\n    deployed_site=\"$site\",\r\n    type=\"$type\",\r\n    name=\"$device\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "description": "Overall CPU Utilization over last 5 minutes",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by (name) (\r\n    irate(\r\n      node_cpu_seconds_total{\r\n        job=\"node_exporter\",\r\n        deployed_site=\"$site\",\r\n        type=\"$type\",\r\n        name=\"$device\",\r\n        mode=\"idle\"\r\n      }[5m]\r\n    )\r\n  ) * 100\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "RAM Utilization",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"node_exporter\", deployed_site=\"$site\", type=\"$type\", name=\"$device\"} / node_memory_MemTotal_bytes{job=\"node_exporter\", deployed_site=\"$site\", type=\"$type\", name=\"$device\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage (/)",
   "type": "gauge",
   "description": "Root filesystem utilization",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_filesystem_avail_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=\"$site\",\r\n      type=\"$type\",\r\n      name=\"$device\",\r\n      mountpoint=\"/\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n    /\r\n    node_filesystem_size_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=\"$site\",\r\n      type=\"$type\",\r\n      name=\"$device\",\r\n      mountpoint=\"/\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Live Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "K7-APP Log Stream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{deployed_site=\"$site\", name=\"$device\", type=\"$type\", job=\"k7-app\"}"
    }
   ]
  },
  {
   "title": "RUBIX Log Stream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{deployed_site=\"$site\", name=\"$device\", type=\"$type\", job=\"rubix\"}"
    }
   ]
  },
  { "title": "Histograms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Usage over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by (name) (\r\n    irate(\r\n      node_cpu_seconds_total{\r\n        job=\"node_exporter\",\r\n        deployed_site=\"$site\",\r\n        type=\"$type\",\r\n        name=\"$device\",\r\n        mode=\"idle\"\r\n      }[5m]\r\n    )\r\n  ) * 100\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by mode",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg by (mode) (\r\n  irate(\r\n    node_cpu_seconds_total{\r\n      job=\"node_exporter\",\r\n      deployed_site=\"$site\",\r\n      type=\"$type\",\r\n      name=\"$device\",\r\n      mode!=\"idle\"\r\n    }[5m]\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{\r\n  job=\"node_exporter\",\r\n  deployed_site=\"$site\",\r\n  type=\"$type\",\r\n  name=\"$device\"\r\n}\r\n",
     "legendFormat": "{{chip}} / {{sensor}}"
    }
   ]
  },
  {
   "title": "Memory Usage over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_memory_MemAvailable_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=\"$site\",\r\n      type=\"$type\",\r\n      name=\"$device\"\r\n    }\r\n    /\r\n    node_memory_MemTotal_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=\"$site\",\r\n      type=\"$type\",\r\n      name=\"$device\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Usage over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_filesystem_avail_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=\"$site\",\r\n      type=\"$type\",\r\n      name=\"$device\",\r\n      mountpoint=\"/\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n    /\r\n    node_filesystem_size_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=\"$site\",\r\n      type=\"$type\",\r\n      name=\"$device\",\r\n      mountpoint=\"/\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O Over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{\r\n  job=\"node_exporter\",\r\n  deployed_site=\"$site\",\r\n  type=\"$type\",\r\n  name=\"$device\"\r\n}[5m])\r\n",
     "legendFormat": "{{device}} Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{\r\n  job=\"node_exporter\",\r\n  deployed_site=\"$site\",\r\n  type=\"$type\",\r\n  name=\"$device\"\r\n}[5m])\r\n",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  {
   "title": "Network Tx/Rx over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (device) (\r\n  rate(node_network_receive_bytes_total{\r\n    job=\"node_exporter\",\r\n    deployed_site=\"$site\",\r\n    type=\"$type\",\r\n    name=\"$device\",\r\n    device!~\"lo\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{device}} Rx"
    },
    {
     "expr": "sum by (device) (\r\n  rate(node_network_transmit_bytes_total{\r\n    job=\"node_exporter\",\r\n    deployed_site=\"$site\",\r\n    type=\"$type\",\r\n    name=\"$device\",\r\n    device!~\"lo\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{device}} Tx"
    }
   ]
  }
 ]
}