{
 "title": "Fleet Overview",
 "description": "Overview of all the on client basis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "site",
    "query": {
     "query": "label_values(up{job=\"node_exporter\"}, deployed_site)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(up{job=\"node_exporter\", deployed_site=~\"$site\"}, type)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(up{job=\"node_exporter\", deployed_site=~\"$site\", type=~\"$type\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total In Current Selection",
   "type": "stat",
   "description": "Count of total devices in current selection",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  up{\r\n    job=\"node_exporter\",\r\n    deployed_site=~\"$site\",\r\n    type=~\"$type\",\r\n    name=~\"$device\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devices By Type",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "count by (type) (\r\n  up{\r\n    job=\"node_exporter\",\r\n    deployed_site=~\".*\",\r\n    type=~\".*\",\r\n    name=~\".*\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (type) (\r\n  up{\r\n    job=\"node_exporter\",\r\n    deployed_site=~\".*\",\r\n    type=~\".*\",\r\n    name=~\".*\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reachstackers Per Site",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "count by (deployed_site) (\r\n  up{\r\n    job=\"node_exporter\",\r\n    deployed_site=~\".*\",\r\n    type=\"reach_stackers\",\r\n    name=~\".*\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (deployed_site) (\r\n  up{\r\n    job=\"node_exporter\",\r\n    deployed_site=~\".*\",\r\n    type=\"reach_stackers\",\r\n    name=~\".*\"\r\n  }\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Active In Current Selection",
   "type": "stat",
   "description": "Count of Active devices in current selection",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  up{\r\n    job=\"node_exporter\",\r\n    deployed_site=~\"$site\",\r\n    type=~\"$type\",\r\n    name=~\"$device\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device Overview",
   "type": "table",
   "gridPos": { "h": 35, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "up{job=\"node_exporter\", deployed_site=~\"$site\", type=~\"$type\", name=~\"$device\"}\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "time()\r\n-\r\nmax_over_time(\r\n  timestamp(\r\n    up{job=\"node_exporter\", deployed_site=~\"$site\", type=~\"$type\", name=~\"$device\"} == 1\r\n  )[48h:]\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - node_boot_time_seconds{\r\n  job=\"node_exporter\",\r\n  deployed_site=~\"$site\",\r\n  type=~\"$type\",\r\n  name=~\"$device\"\r\n}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (\r\n  avg by (name) (\r\n    irate(node_cpu_seconds_total{\r\n      job=\"node_exporter\",\r\n      deployed_site=~\"$site\",\r\n      type=~\"$type\",\r\n      name=~\"$device\",\r\n      mode=\"idle\"\r\n    }[5m])\r\n  ) * 100\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_memory_MemAvailable_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=~\"$site\",\r\n      type=~\"$type\",\r\n      name=~\"$device\"\r\n    }\r\n    /\r\n    node_memory_MemTotal_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=~\"$site\",\r\n      type=~\"$type\",\r\n      name=~\"$device\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_filesystem_avail_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=~\"$site\",\r\n      type=~\"$type\",\r\n      name=~\"$device\",\r\n      mountpoint=\"/\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n    /\r\n    node_filesystem_size_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=~\"$site\",\r\n      type=~\"$type\",\r\n      name=~\"$device\",\r\n      mountpoint=\"/\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (name) (\r\n  node_hwmon_temp_celsius{\r\n    job=\"node_exporter\",\r\n    deployed_site=~\"$site\",\r\n    type=~\"$type\",\r\n    name=~\"$device\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" },
    { "legendFormat": "__auto" },
    { "legendFormat": "__auto" },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}