{
 "title": "Promki",
 "description": "Promtail + Loki",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Deployed Site",
    "query": {
     "query": "label_values(up{job=\"node_exporter\"}, deployed_site)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(up{job=\"node_exporter\", deployed_site=\"$site\"}, type)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(up{job=\"node_exporter\", deployed_site=\"$site\", type=\"$type\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rechability",
     "type": "stat",
     "description": "1=Up, 0=Down",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"node_exporter\", deployed_site=\"$site\", type=\"$type\", instance=\"$device\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - node_boot_time_seconds{\r\n  job=\"node_exporter\",\r\n  deployed_site=\"$site\",\r\n  type=\"$type\",\r\n  instance=\"$device\"\r\n}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gateway Latency",
     "type": "stat",
     "description": "Latency to default gateway",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPS",
     "type": "stat",
     "description": "Is GPS Connected?\nIs /dev/ublox_gnss File present?",
     "gridPos": { "h": 2, "w": 4, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "# here check if that device file is present or not",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RTK",
     "type": "stat",
     "description": "Displayed RTK value.\n-1 NO DGPS\n0 DGPS\n1 FLOAT\n2 FIX",
     "gridPos": { "h": 2, "w": 4, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Device Datetime",
     "type": "stat",
     "description": "Displayed Device date time. (only time is displayed if date is today)",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1000 * node_time_seconds{\r\n  job=\"node_exporter\",\r\n  deployed_site=\"$site\",\r\n  type=\"$type\",\r\n  instance=\"$device\"\r\n}\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Guages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Temperature",
     "type": "gauge",
     "description": "Max hwmon Temperature",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (instance) (\r\n  node_hwmon_temp_celsius{\r\n    job=\"node_exporter\",\r\n    deployed_site=\"$site\",\r\n    type=\"$type\",\r\n    instance=\"$device\"\r\n  }\r\n)\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "description": "Overall CPU Utilization over last 5 minutes",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (\r\n  avg by (instance) (\r\n    irate(\r\n      node_cpu_seconds_total{\r\n        job=\"node_exporter\",\r\n        deployed_site=\"$site\",\r\n        type=\"$type\",\r\n        instance=\"$device\",\r\n        mode=\"idle\"\r\n      }[5m]\r\n    )\r\n  ) * 100\r\n)\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "description": "RAM Utilization",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"node_exporter\", deployed_site=\"$site\", type=\"$type\", instance=\"$device\"} / node_memory_MemTotal_bytes{job=\"node_exporter\", deployed_site=\"$site\", type=\"$type\", instance=\"$device\"}))\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Usage (/)",
     "type": "gauge",
     "description": "Root filesystem utilization",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\r\n  1 - (\r\n    node_filesystem_avail_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=\"$site\",\r\n      type=\"$type\",\r\n      instance=\"$device\",\r\n      mountpoint=\"/\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n    /\r\n    node_filesystem_size_bytes{\r\n      job=\"node_exporter\",\r\n      deployed_site=\"$site\",\r\n      type=\"$type\",\r\n      instance=\"$device\",\r\n      mountpoint=\"/\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n  )\r\n)\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Histograms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true
  }
 ]
}